let catData={"categories":[
    {"category":"Deviation", "colour":"#E6B00F",
    "description":"Emphasise variations (+/-) from a fixed reference point. Typically the reference point is zero but it can also be a target or a long-term average. Can also be used to show sentiment (positive/neutral/negative)",
    "example":"Trade surplus/deficit, climate change"},
    {"category":"Correlation", "colour":"#977348",
    "description":"Show the relationship between two or more variables. Be mindful that, unless you tell them otherwise, many readers will assume the relationships you show them to be causal (i.e. one causes the other)",
    "example":"Trade surplus/deficit, climate change"},
{"category":"Change v Time", "colour":"#28903B",
	"description":"Give emphasis to changing trends. These can be short (intra-day) movements or extended series traversing decades or centuries: Choosing the correct time period is important to provide suitable context for the reader",
	"example":"Trade surplus/deficit, climate change"},
{"category":"Ranking", "colour":"#008EB0",
    "description":"Use where an item’s position in an ordered list is more important than its absolute or relative value. Don’t be afraid to highlight the points of interest.",
    "example":"Trade surplus/deficit, climate change"},
{"category":"Distribution", "colour":"#F26522",
	"description":"Show values in a dataset and how often they occur. The shape (or ‘skew’) of a distribution can be a memorable way of highlighting the lack of uniformity or equality in the data",
	"example":"Trade surplus/deficit, climate change"},
{"category":"Part to whole", "colour":"#0054A6",
    "description":"Show how a single entity can be broken down into its component elements. If the reader’s interest is solely in the size of the components, consider a magnitude-type chart instead",
    "example":"Trade surplus/deficit, climate change"},
{"category":"Magnitude", "colour":"#A3488C",
"description":"Show size comparisons. These can be relative (just being able to see larger/bigger) or absolute (need to see fine differences). Usually these show a ‘counted’ number (for example, barrels, dollars or people) rather than a calculated rate or per cent",
"example":"Trade surplus/deficit, climate change"},
{"category":"Spatial", "colour":"#9C9D94",
"description":"Used only when precise locations or geographical patterns in data are more important to the reader than anything else. ",
"example":"Trade surplus/deficit, climate change"},
{"category":"Flow", "colour":"#ABBD67",
"description":"Show the reader volumes or intensity of movement between two or more states or conditions. These might be logical sequences or geographical locations",
"example":"Trade surplus/deficit, climate change"}]
}

