
var styleprint = {classes:
[{class:"background{fill: none}"},
{class:"chartholder{fill: #fff1e0}"},
{class:"title{font-size:12px; fill: #000000; font-weight: 600;}"},
{class:"subtitle{fill:#000000; font-size: 9.6px; font-weight: 400;}"},
{class:"labels{font-size:10px; fill: #ffffff; font-weight: 300;}"},
{class:"source{fill: #000000; font-size: 7.2px; font-weight: 400;}"},
{class:"logo{fill: #dacfc5;}"},
{class:"hat{fill:none; stroke-width:0.3px; stroke:#22190f;}"},
{class:"xAxis{fill:none; stroke-width:0px; stroke:none;}"},
{class:"xAxis line{fill:none; stroke-width:.3px; stroke:#000000;}"},
{class:"xAxis text{fill:#000000; font-size: 9.6px; font-weight: 400; font-feature-settings:'tnum' 1;}"},
{class:"yAxis{fill:none; stroke-width:0px; stroke:none;}"},
{class:"yAxis line{fill:none; stroke-width:0.3px; stroke:#000000;}"},
{class:"yAxis text{fill:#000000; font-size: 9.6px; font-weight: 400; font-feature-settings: 'tnum' 1;}"},
{class:"origin line{fill:none; stroke-width:0.6px;}"},
{class:"whiskers{fill:none; stroke-width:1.0px;stroke:#22190f;}"},
{class:"lines{fill:none; stroke-width:2.0px;stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.8px;stroke-linecap: round;}"},
{class:"fill{opacity: .38}"},
{class:"highlight{fill-opacity:1.0;}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"month{fill:none; stroke: #000000; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"link{fill:none; stroke:#000000; opacity: 0.20;}"},
{class:"node{fill:#000000;}"}
],
titleOffset:10,
subOffset:0,
legendyOffset:0,
linecolours:["#006a93","#ddb831","#c6d6cc","#55a2c7","#ad1c21","#486ba0"],
fillcolours:["#006a93","#ddb831","#c6d6cc","#55a2c7","#ad1c21","#486ba0","#ddb831"]
}

var styleweb = {classes:
[{class:"background{fill: none}"},
{class:"chartholder{fill: none;}"},
{class:"title{font-size:25px; font-weight: 400; fill: #3b3d3b;}"},
{class:"subtitle{font-size:18px; font-weight: 400; fill: #6b6e68;}"},
{class:"source{fill: #6b6e68; font-size: 14.0px; font-weight: 400;}"},
{class:"labels{font-size:12px; fill: #ffffff; font-weight: 600;}"},
{class:"logo{fill: #dacfc5;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke-width: 1.0px; stroke:#c3bcb0; stroke-dasharray:1,2;}"},
{class:"xAxis text{fill:#6b6e68; font-size: 18.0px; font-weight: 400;}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 1.0px; stroke:#c3bcb0; stroke-dasharray:1,2;}"},
{class:"yAxis text{fill:#6b6e68; font-size: 18.0px; font-weight: 400; font-feature-settings: 'tnum' 1; text-anchor: end;}"},
{class:"origin line{fill:none; stroke:#9ba497; stroke-width: 1px;stroke-dasharray:1,0}"},
{class:"whiskers{fill:none; stroke-width:1.0px;stroke:#22190f;}"},
{class:"lines{fill:none; stroke-width: 2.5px; stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.8px;stroke-linecap: round;}"},
{class:"fill{opacity: .38}"},
{class:"highlight{fill-opacity:1.0;}"},
{class:"day{fill:none;stroke: #fff1e0; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"month{fill:none;stroke: #000000; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"link{fill:none; stroke:#000000; opacity: 0.20;}"},
{class:"node{fill:#000000;}"}
],
titleOffset:21,
subOffset:0,
legendyOffset:0,
linecolours:["#A5526A","#F19F9E","#D36969","#69A1AA","#66bfd4","#486ba0"],
fillcolours:["#A5526A","#F19F9E","#D36969","#69A1AA","#66bfd4","#486ba0","#F19F9E"]
}

var stylesoc = {classes:
[{class:"background{fill: #212121;}"},
{class:"chartholder{fill: #6b6e68;}"},
{class:"title{font-size: 38px; fill: #ffffff; font-weight: 600; opacity: 0.9;}"},
{class:"subtitle{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.7;}"},
{class:"labels{font-size: 38px; fill: #ffffff; opacity: 0.95; font-weight: 400;}"},
{class:"source{font-size: 25px; fill: #ffffff; font-weight: 400; opacity: 0.5;}"},
{class:"logo{fill: #ffffff; opacity: 0.38;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke:#ffffff; stroke-width: 2.0px; stroke-dasharray:2,8; opacity: 0.5;}"},
{class:"xAxis text{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.5;}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 2.0px; stroke-dasharray:2,8; opacity: 0.38; stroke:#ffffff;}"},
{class:"yAxis text{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.5; font-feature-settings: 'tnum' 1; text-anchor: end;}"},
{class:"origin line{fill:none; stroke:#ffffff; stroke-width: 2.0px; opacity: 0.5; stroke-dasharray: 1,0}"},
{class:"whiskers{fill:none; stroke-width:2.0px;stroke:#ffffff; opacity: 0.5}"},
{class:"lines{fill:none; stroke-width: 5px;  stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.8px;stroke-linecap: round;}"},
{class:"fill{opacity: .38}"},
{class:"highlight{fill-opacity:1.0;}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:1.0px; opacity: 0.5; stroke-linecap: round;}"},
{class:"month{fill:none; stroke: #ffffff; stroke-width:1.0px; opacity: 0.5; stroke-linecap: round;}"},
{class:"link{fill:none; stroke:#ffffff; opacity: 0.20;}"},
{class:"node{fill:#000000; }"}
],
titleOffset:36,
subOffset:0,
legendyOffset:0,
linecolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"],
fillcolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"]
}

var stylevid = {classes:
[{class:"background{fill: #dfd0bd;}"},
{class:"titleframe{fill: #757575;}"},
{class:"chartholder{fill: none;}"},
{class:"title{font-size: 68px; fill: #ffffff; font-weight: 600;}"},
{class:"subtitle{font-size: 48; fill: #000000; font-weight: 600;}"},
{class:"source{font-size: 44; fill: #000000; font-weight: 600;}"},
{class:"labels{font-size:10px; fill: #ffffff; font-weight: 300;}"},
{class:"logo{fill: #ffffff;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke-width: 5.0px; stroke:#ffffff;}"},
{class:"xAxis text{font-size: 48; fill: #000000; font-weight: 600;}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 5.0px; stroke:#ffffff;}"},
{class:"yAxis text{font-size: 48; fill: #000000; font-weight: 600;font-feature-settings: 'tnum' 1; text-anchor: end;}"},
{class:"origin line{fill:none; stroke:#ffffff; stroke-width: 5.0px;stroke-dasharray:1,0}"},
{class:"whiskers{fill:none; stroke-width:2.0px;stroke:#ffffff; opacity: 0.5}"},
{class:"lines{fill:none; stroke-width: 8.0px; stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.8px;stroke-linecap: round;}"},
{class:"fill{opacity: .38}"},
{class:"highlight{fill-opacity:1.0;}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:1.0px; opacity: 0.5; stroke-linecap: round;}"},
{class:"month{fill:none; stroke: #ffffff; stroke-width:1.0px; opacity: 0.5; stroke-linecap: round;}"},
{class:"link{fill:none; stroke:#ffffff; opacity: 0.20;}"},
{class:"node{fill:#000000; }"}

],
titleOffset:68,
subOffset:0,
legendyOffset:15,
linecolours:["#b34b41","#5a8caf","#9baa6e","#eda45e","#9c5f87","#486ba0"]
}
