
var styleprint = {classes:
[{class:"background{fill: none}"},
{class:"annotationText{fill:#000000;font-size:9.6px;}"},
{class:"annotationLine{fill:none;stroke:#000000;stroke-width:1px}"},
{class:"Shade{fill:#55a2c7;opacity:0.2;stroke:none}"},
{class:"chartholder{fill: none}"},
{class:"title{font-size:12px; fill: #000000; font-weight: 600;}"},
{class:"subtitle{fill:#000000; font-size: 9.6px; font-weight: 400;}"},
{class:"source{fill: #000000; font-size: 7.2px; font-weight: 400;}"},
{class:"logo{fill: #dacfc5;}"},
{class:"hat{fill:none; stroke-width:0.3px; stroke:#22190f;}"},
{class:"xAxis{fill:none; stroke-width:0px; stroke:none;}"},
{class:"xAxis line{fill:none; stroke-width:.3px; stroke:#000000;}"},
{class:"xAxis text{fill:#000000; font-size: 9.6px; font-weight: 400; font-feature-settings:'tnum' 1;text-anchor: middle;}"},
{class:"minorAxis{fill:none; stroke-width:0px; stroke:none;}"},
{class:"minorAxis line{fill:none; stroke-width:0.3px; stroke:#000000;}"},
{class:"yAxis{fill:none; stroke-width:0px; stroke:none;}"},
{class:"yAxis line{fill:none; stroke-width:0.3px; stroke:#000000;}"},
{class:"yAxis text{fill:#000000; font-size: 9.6px; font-weight: 400; font-feature-settings: 'tnum' 1;text-anchor: end;}"},
{class:"minorAxis{fill:none; stroke-width:0px; stroke:none;}"},
{class:"minorAxis line{fill:none; stroke-width:0.3px; stroke:#000000;}"},
{class:"xAxis line{fill:none; stroke-width:.3px; stroke:#000000;}"},
{class:"origin line{fill:none; stroke-width:0.6px;}"},
{class:"area{fill:#D9E7EF;}"},
{class:"lines{fill:none; stroke-width:2.0px;stroke-linecap: round;stroke-linejoin: round;}"}
],
titleOffset:10,
subOffset:0,
legendyOffset:0,
linecolours:["#006a93","#ddb831","#c6d6cc","#55a2c7","#ad1c21","#486ba0"],
fillcolours:["#006a93","#ddb831","#c6d6cc","#55a2c7","#ad1c21","#486ba0"]
}

var styleweb = {classes:
[{class:"background{fill: none}"},
{class:"annotationText{fill:#6b6e68;font-size:18px;}"},
{class:"annotationLine{fill:none;stroke:#6b6e68;stroke-width:1px}"},
{class:"Shade{fill:#69A1AA;opacity:0.2;stroke:none}"},
{class:"chartholder{fill: none;}"},
{class:"title{font-size:25.0px; font-weight: 400; fill: #3b3d3b;}"},
{class:"subtitle{font-size:18.0px; font-weight: 400; fill: #6b6e68;}"},
{class:"source{fill: #6b6e68; font-size: 14.0px; font-weight: 400;}"},
{class:"logo{fill: #dacfc5;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke-width: 1.0px; stroke:#c3bcb0;}"},
{class:"xAxis text{fill:#6b6e68; font-size: 18.0px; font-weight: 400;text-anchor: middle;}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 1.0px; stroke:#c3bcb0; stroke-dasharray:1,2}"},
{class:"yAxis text{fill:#6b6e68; font-size: 18.0px; font-weight: 400; font-feature-settings: 'tnum' 1; text-anchor: end;}"},
{class:"minorAxis{fill:none; stroke: none;}"},
{class:"minorAxis line{fill:none; stroke:#9ba497; stroke-width: 1px;stroke-dasharray:1,0}"},
{class:"origin line{fill:none; stroke:#9ba497; stroke-width: 1px;stroke-dasharray:1,0}"},
{class:"area{fill:#D9E7EF;}"},
{class:"lines{fill:none; stroke-width: 2.5px; stroke-linecap: round; stroke-linejoin: round;}"}
],
titleOffset:21,
subOffset:0,
legendyOffset:0,
linecolours:["#A5526A","#F19F9E","#D36969","#69A1AA","#66bfd4","#486ba0"],
fillcolours:["#A5526A","#F19F9E","#D36969","#69A1AA","#66bfd4","#486ba0"]
}

var stylenowcast = {classes:
[{class:"background{fill: none}"},
{class:"annotationText{fill:#6b6e68;font-size:14px;}"},
{class:"annotationLine{fill:none;stroke:#6b6e68;stroke-width:1px}"},
{class:"Shade{fill:#69A1AA;opacity:0.2;stroke:none}"},
{class:"chartholder{fill: none}"},
{class:"title{font-size:21.0px; font-weight: 400; fill: #3b3d3b;}"},
{class:"subtitle{font-size:14.0px; font-weight: 400; fill: #6b6e68;}"},
{class:"source{fill: #6b6e68; font-size: 12.5px; font-weight: 400;}"},
{class:"logo{fill: #dacfc5;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke-width: 1.0px; stroke:#c3bcb0;}"},
{class:"xAxis text{fill:#6b6e68; font-size: 14.0px; font-weight: 400; text-anchor: middle; font-feature-settings: 'tnum' 1;}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 1.0px; stroke:#c3bcb0; stroke-dasharray:1,2}"},
{class:"yAxis text{fill:#6b6e68; font-size: 14.0px; font-weight: 400; font-feature-settings: 'tnum' 1; text-anchor: end;}"},
{class:"minorAxis{fill:none; stroke: none;}"},
{class:"minorAxis line{fill:none; stroke:#9ba497; stroke-width: 1px;stroke-dasharray:1,0}"},
{class:"origin line{fill:none; stroke:#9ba497; stroke-width: 1px;stroke-dasharray:1,0}"},
{class:"area{fill:#D9E7EF;}"},
{class:"lines{fill:none; stroke-width: 2.5px; stroke-linecap: round;stroke-linejoin: round;}"}
],
titleOffset:21,
subOffset:0,
legendyOffset:0,
linecolours:["#A5526A","#F19F9E","#D36969","#69A1AA","#66bfd4","#486ba0"],
fillcolours:["#A5526A","#F19F9E","#D36969","#69A1AA","#66bfd4","#486ba0"]
}

var stylesoc = {classes:
[{class:"background{fill: #212121;}"},
{class:"annotationText{fill:#ffffff;font-size:18px;}"},
{class:"annotationLine{fill:none;stroke:#ffffff;stroke-width:1px}"},
{class:"Shade{fill:#ffffff;opacity:0.2;stroke:none}"},
{class:"chartholder{fill: none;}"},
{class:"title{font-size: 38px; fill: #ffffff; font-weight: 600; opacity: 0.9;}"},
{class:"subtitle{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.7;}"},
{class:"source{font-size: 25px; fill: #ffffff; font-weight: 400; opacity: 0.5;}"},
{class:"logo{fill: #ffffff; opacity: 0.38;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke:#ffffff; stroke-width: 2.0px; opacity: 0.5;}"},
{class:"xAxis text{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.5;}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 2.0px; stroke-dasharray:2,8; opacity: 0.38; stroke:#ffffff;}"},
{class:"yAxis text{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.5; font-feature-settings: 'tnum' 1; text-anchor: end;}"},
{class:"minorAxis{fill:none; stroke: none;}"},
{class:"minorAxis line{fill:none; stroke:#ffffff; stroke-width: 2.0px; opacity: 0.5; stroke-dasharray: 1,0}"},
{class:"origin line{fill:none; stroke:#ffffff; stroke-width: 2.0px; opacity: 0.5; stroke-dasharray: 1,0}"},
{class:"area{fill:#fdf8f2; fill-opacity:0.2;}"},
{class:"lines{fill:none; stroke-width: 5px;  stroke-linecap: round;stroke-linejoin: round;}"}
],
titleOffset:36,
subOffset:0,
legendyOffset:0,
linecolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"],
fillcolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"]
}

var stylevid = {classes:
[{class:"background{fill: #212121;}"},
{class:"titleframe{fill: none;}"},
{class:"annotationText{fill:#ffffff;font-size:48px;}"},
{class:"annotationLine{fill:none;stroke:#ffffff;stroke-width:1px}"},
{class:"Shade{fill:#ffffff;opacity:0.2;stroke:none}"},
{class:"chartholder{fill: none;}"},
{class:"title{font-size: 68px; fill: #ffffff; font-weight: 600;opacity: 0.9;}"},
{class:"subtitle{font-size: 48; fill: #ffffff; font-weight: 400;opacity: 0.7;}"},
{class:"source{font-size: 36; fill: #ffffff; font-weight: 400;opacity: 0.5;}"},
{class:"logo{fill: #ffffff;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke-width: 4px; stroke:#ffffff;opacity: 0.5}"},
{class:"xAxis text{font-size: 48; fill: #ffffff; font-weight: 400;opacity: 0.5}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 4px; stroke:#ffffff;opacity: 0.38}"},
{class:"yAxis text{font-size: 48; fill: #ffffff; font-weight: 400;font-feature-settings: 'tnum' 1; text-anchor: end;opacity: 0.5}"},
{class:"origin line{fill:none; stroke:#ffffff; stroke-width: 5.0px;stroke-dasharray:1,0; opacity: 0.5}"},
{class:"area{fill:#fdf8f2; fill-opacity:0.2;}"},
{class:"whiskers{fill:none; stroke-width:2.0px;stroke:#ffffff; opacity: 0.5}"},
{class:"lines{fill:none; stroke-width: 8.0px; stroke-linecap: round;stroke-linejoin: round;}"},
{class:"fill{fill-opacity:1.0; stroke-width: 0.0px}"},
{class:"highlight{fill-opacity:1.0;}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:4.0px; opacity: 0.5; stroke-linecap: round;stroke-linejoin: round;}"},
{class:"month{fill:none; stroke: #ffffff; stroke-width:4.0px; opacity: 0.5; stroke-linecap: round;stroke-linejoin: round;}"}

],
titleOffset:68,
subOffset:0,
legendyOffset:15,
linecolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"],
fillcolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"]
}
